# Generated by Django 5.1.6 on 2025-02-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_userprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_city',
            field=models.CharField(default='не указано', max_length=32),
        ),
    ]
