# Generated by Django 5.1.6 on 2025-02-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_review_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_city',
            new_name='country',
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_ru',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
