# Generated by Django 5.1.6 on 2025-02-09 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_rename_user_city_userprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.hotel'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_name_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.hotel'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_name_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.hotel'),
        ),
    ]
