# Generated by Django 5.1.6 on 2025-02-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_alter_rooms_room_name_alter_rooms_room_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='room_name_en',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='room_name_ru',
        ),
    ]
