# Generated by Django 5.1.6 on 2025-02-11 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_remove_rooms_room_name_en_remove_rooms_room_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='bron',
            name='price',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_hotel', to='room.city'),
        ),
        migrations.AlterField(
            model_name='roomimages',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_image', to='room.rooms'),
        ),
    ]
