# Generated by Django 5.1.6 on 2025-02-11 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_bron_price_alter_hotel_city_alter_roomimages_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='hotel_review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review_hotel', to='room.hotel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bron',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_bron', to='room.rooms'),
        ),
        migrations.AlterField(
            model_name='review',
            name='room_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_room', to='room.hotel'),
        ),
    ]
